### ISSUE TITLE
I wanna this :)

### ISSUE THREAD

**Issue by MioGreen** [ionic-team/ionic-theme-server#1]
Guys, when you public this? I am not designer and want to buy or download custom themes for ionic! And by the way thank you for your framework.

**Comment by adamdbradley** [comment]
Greetings @MioGreen!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
